### ISSUE TITLE
Bug in class extension via visitor implementation on @asjson

### ISSUE THREAD

**Issue by derekbar90** [SteerProtocol/concentrated-liquidity-strategy-assemblyscript#9]
Class extends ExecutionContext, but parent class not found. Maybe add the @json decorator over parent class?

Recreation Steps: https://github.com/SteerProtocol/donchian-channel-strategy

run build, the issue exists because we have two dependencies in which one is extending another in a file in the main project. Do the imports just need to be adjusted?

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Bug in class extension via visitor implementation on @asjson**
  - The parent class is not found when the class extends ExecutionContext
  - The @json decorator may need to be added over the parent class
  - Recreation Steps: https://github.com/SteerProtocol/donchian-channel-strategy
  - Running the build reproduces the issue
  - There are two dependencies in the project, one extending another in a file in the main project
  - Verify if the imports need to be adjusted

**Comment by JairusSW** [comment]
I'll resolve this when I get home after school

**Comment by JairusSW** [comment]
Its really just fine. The warning is there because of the order in which libraries are parsed, so the X class is parsed before ExecutionContext is ever seen, but ExecutionContext is visited, so its all good.

I'll push a version out that has better error descriptors

**Comment by JairusSW** [comment]
Resolved with https://www.npmjs.com/package/json-as/v/0.6.5
